name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/gitee-mirror-action@master
        with:
          src: github/gcdxuzhiwei
          dst: gitee/suesxuzhiwei
          dst_key: ${{ secrets.GITEE_PASSWORD }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          white_list: shop-review-generator
          account_type: user
          force_update: true
